platform :ios,'9.0'
use_frameworks!
target 'Study Problem' do
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'RSKImageCropper'
pod 'SVProgressHUD'
pod 'JSQMessagesViewController'
pod 'DZNEmptyDataSet'
pod 'BubbleTransition', '~> 2.0.0'
pod 'DKImagePickerController'
end
