platform :ios,'9.0'
use_frameworks!
target 'Study Problem' do
pod 'SwiftDate'
pod 'SlideMenuControllerSwift'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'RSKImageCropper'
pod 'SVProgressHUD'
pod 'RealmSwift'
end
